spring.application.name=brest_cancer
server.port=8080

# ML Service
ml.base-url=http://localhost:8001
ml.timeout-ms=3000

management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration