spring.application.name=brest_cancer
server.port=8080

# ML Service
ml.base-url=http://localhost:8001
ml.timeout-ms=3000

# PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5433/breast_cancer_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info

# Swagger
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs